"""Generate src/core/anchors.inc from src/core/anchors.txt and the read-only research\\RDR.exe copy.

Every expected byte string comes from the exe itself, so an anchor's RVA is the only thing a human (or an
agent's notes) supplies, and the runtime check proves that RVA still points at the same code.

    python tools/gen_anchors.py            # writes src/core/anchors.inc
    python tools/gen_anchors.py --check    # exit 1 if anchors.inc is stale

Spec line: name kind rva [nbytes]; kind is func (default 12 bytes), site (nbytes required) or global.
"""
import pathlib
import sys

import pefile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / 'src' / 'core' / 'anchors.txt'
OUT = ROOT / 'src' / 'core' / 'anchors.inc'
EXE = ROOT / 'research' / 'RDR.exe'


def main() -> int:
    pe = pefile.PE(str(EXE), fast_load=True)
    data = pe.__data__
    lines = [
        '// Generated by tools/gen_anchors.py from src/core/anchors.txt and research/RDR.exe. Do not edit.',
        f'// RDR.exe TimeDateStamp {pe.FILE_HEADER.TimeDateStamp:#x}, SizeOfImage {pe.OPTIONAL_HEADER.SizeOfImage:#x}.',
        f'#define RDRVR_EXE_TIMESTAMP {pe.FILE_HEADER.TimeDateStamp:#x}u',
        f'#define RDRVR_EXE_SIZEOFIMAGE {pe.OPTIONAL_HEADER.SizeOfImage:#x}u',
        '// ANCHOR(name, kind, rva, byte count, expected bytes)',
    ]
    names = set()
    for raw in SPEC.read_text().splitlines():
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        name, kind, rva = parts[0], parts[1], int(parts[2], 16)
        if name in names:
            raise SystemExit(f'duplicate anchor {name}')
        names.add(name)
        if kind == 'global':
            lines.append(f'ANCHOR({name}, Global, {rva:#x}, 0, "")')
            continue
        n = int(parts[3]) if len(parts) > 3 else (12 if kind == 'func' else 0)
        if kind not in ('func', 'site') or n <= 0:
            raise SystemExit(f'bad spec line: {raw}')
        off = pe.get_offset_from_rva(rva)
        hexs = ''.join(f'\\x{b:02x}' for b in data[off:off + n])
        lines.append(f'ANCHOR({name}, {"Func" if kind == "func" else "Site"}, {rva:#x}, {n}, "{hexs}")')
    text = '\n'.join(lines) + '\n'
    if '--check' in sys.argv:
        current = OUT.read_text() if OUT.exists() else ''
        if current != text:
            print('anchors.inc is stale: run tools/gen_anchors.py')
            return 1
        print('anchors.inc up to date')
        return 0
    OUT.write_text(text)
    print(f'wrote {OUT} ({len(names)} anchors)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
