"""Generate src/core/anchors_sig.inc: what the build report (anchors.cpp, run when RDR.exe is not the analysed build)
looks for in another build of the game, from src/core/anchors.txt and the read-only research\\RDR.exe copy.

- For each code anchor (func, site): 32, 64 or 128 bytes from its RVA (the shortest unique in our .text) with the
  parts that move when code moves masked out (the rel32 of calls and jumps, the disp32 of RIP-relative operands).
- For each global anchor: up to three instructions that address it RIP-relatively (and the bytes after them, masked
  the same way), each unique in our .text: in another build, the instruction found and its disp32 give where that
  build keeps the global.

    python tools/gen_buildsig.py            # writes src/core/anchors_sig.inc (takes a minute: it disassembles .text)
"""
import pathlib
import sys

import capstone
import pefile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / 'src' / 'core' / 'anchors.txt'
OUT = ROOT / 'src' / 'core' / 'anchors_sig.inc'
EXE = ROOT / 'research' / 'RDR.exe'
SIG_LENS = (32, 64, 128)  # the shortest that is unique in our .text (stubs stay not unique: the report places them by a neighbour)
REF_LEN = 24
MAX_REFS = 3


def main() -> int:
    pe = pefile.PE(str(EXE), fast_load=True)
    pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_EXCEPTION']])
    text = next(s for s in pe.sections if s.Name.rstrip(b'\0') == b'.text')
    t_rva, t_size = text.VirtualAddress, max(text.Misc_VirtualSize, text.SizeOfRawData)
    t_data = text.get_data()[:t_size]
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    md.detail = True

    def masked(rva, n):
        """n bytes from rva, the moving parts masked (0 = don't care); stops at the first undecodable byte"""
        off = rva - t_rva
        b = bytearray(t_data[off:off + n + 16])
        m = bytearray(b'\xff' * len(b))
        pos = 0
        for ins in md.disasm(bytes(b), rva):
            if pos >= n:
                break
            k = ins.address - rva
            if ins.disp_size and any(op.type == capstone.x86.X86_OP_MEM and op.mem.base == capstone.x86.X86_REG_RIP for op in ins.operands):
                for i in range(ins.disp_offset, ins.disp_offset + ins.disp_size):
                    m[k + i] = 0
            if ins.imm_size and ins.group(capstone.CS_GRP_JUMP) | ins.group(capstone.CS_GRP_CALL) and any(
                    op.type == capstone.x86.X86_OP_IMM for op in ins.operands):
                for i in range(ins.imm_offset, ins.imm_offset + ins.imm_size):
                    m[k + i] = 0
            pos = k + ins.size
        return bytes(b[:n]), bytes(m[:n])

    def count(b, m, limit=2):
        """the masked pattern's matches in our .text (up to limit)"""
        anchor = next((i for i in range(len(b) - 3) if m[i] and m[i + 1] and m[i + 2] and m[i + 3]), None)
        if anchor is None:
            return limit
        key = b[anchor:anchor + 4]
        found, start = 0, 0
        while True:
            j = t_data.find(key, start)
            if j < 0:
                return found
            s = j - anchor
            if s >= 0 and all(not m[i] or t_data[s + i] == b[i] for i in range(len(b))):
                found += 1
                if found >= limit:
                    return found
            start = j + 1

    specs = []
    for raw in SPEC.read_text().splitlines():
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        specs.append((parts[0], parts[1], int(parts[2], 16)))

    lines = ['// Generated by tools/gen_buildsig.py from src/core/anchors.txt and research/RDR.exe. Do not edit.',
             '// SIG(name, rva, n, "n bytes", "mask", unique): a code anchor; GREF(name, global rva, site rva, disp offset, end offset,',
             '// "bytes", "mask"): an instruction addressing the global (its disp32 at disp offset, the instruction ending at end offset);',
             '// GNONE(name, global rva, references): a global with no unique reference to find it by.']
    codes = [(n, r) for n, k, r in specs if k in ('func', 'site')]
    globs = {r: n for n, k, r in specs if k == 'global'}
    unique_codes = 0
    for name, rva in codes:
        for n in SIG_LENS:
            b, m = masked(rva, n)
            u = count(b, m) == 1
            if u:
                break
        unique_codes += u
        lines.append('SIG(%s, %#x, %d, "%s", "%s", %d)' % (name, rva, len(b), ''.join('\\x%02x' % x for x in b), ''.join('\\x%02x' % x for x in m),
                                                       1 if u else 0))
    # every RIP-relative reference to a global, by one linear sweep per .pdata function
    refs = {g: [] for g in globs}
    funcs = sorted({(e.struct.BeginAddress, e.struct.EndAddress) for e in getattr(pe, 'DIRECTORY_ENTRY_EXCEPTION', [])})
    for beg, end in funcs:
        if not (t_rva <= beg < t_rva + t_size):
            continue
        code = t_data[beg - t_rva:min(end, t_rva + t_size) - t_rva]
        for ins in md.disasm(code, beg):
            if not ins.disp_size:
                continue
            for op in ins.operands:
                if op.type == capstone.x86.X86_OP_MEM and op.mem.base == capstone.x86.X86_REG_RIP:
                    tgt = ins.address + ins.size + op.mem.disp
                    if tgt in refs and len(refs[tgt]) < 40:
                        refs[tgt].append((ins.address, ins.disp_offset, ins.size))
    found_globals = 0
    for g, name in sorted(globs.items(), key=lambda x: x[1]):
        kept = 0
        for site, doff, size in refs[g]:
            b, m = masked(site, REF_LEN)
            if count(b, m) != 1:
                continue
            lines.append('GREF(%s, %#x, %#x, %d, %d, "%s", "%s")' % (name, g, site, doff, size, ''.join('\\x%02x' % x for x in b),
                                                                   ''.join('\\x%02x' % x for x in m)))
            kept += 1
            if kept >= MAX_REFS:
                break
        found_globals += kept > 0
        if not kept:
            lines.append('GNONE(%s, %#x, %d)  // no unique reference found (of %d)' % (name, g, len(refs[g]), len(refs[g])))
    OUT.write_text('\n'.join(lines) + '\n')
    print('wrote %s: %d code anchors (%d unique), %d of %d globals with references' % (OUT, len(codes), unique_codes, found_globals, len(globs)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
